The Custom Function and an Examples Folder
okbob/plpgsql_check pull request #127
Opened 2022-09-23 16:38 UTC by kirkw

Pavel, 
  I am learning how to do this.  I created a file with the same name and a .md extension for the readme.  I like this approach, but not sure.  Feel free to reject this and tell me to do it correctly.

  My idea behind the examples folder is to NOT clutter up.  Also I may have used UPPER case "Examples".  
Please execute this function in a separate db (I did, but my environment could have some tool installed I accidentally used).

  My hope is to have other variations of this.  As well as to have other contributors.
I may even created a PRIZE offering for submissions of good ideas (Like 4 winners $100,$50,$25,$25 Amazon Gift Cards).
For those that submit good functions and .md files to explain them!

  Thank you, as always for your support in this process.

2022-09-24 18:14 UTC, okbob requested changes

2022-09-24 18:14 UTC, okbob commented on examples/custom_scan_function.sql
> +                SELECT TO_REGPROC(fname)::oid INTO foid;  -- This function will not throw an exception, just returns NULL
please use :=  instead SELECT INTO

2022-09-24 18:14 UTC, okbob commented on examples/custom_scan_function.sql
> +                IF (foid IS NULL) THEN
the brackets should not be used here

2022-09-24 23:17 UTC, kirkw reviewed
It let me edit, but I am new to this.  Let me know if you see the changes the way you expect.

2022-09-25 05:36 UTC, merged

2022-09-25 05:36 UTC, okbob commented
Merged, thank you for PR